<?php
require("./".$prefijo."db/db.mlCiudad.php");
require("./".$prefijo."db/db.mlDepartamento.php");
require("./".$prefijo."db/db.mlHistoria.php");
require("./".$prefijo."db/db.mlLogVoto.php");
require("./".$prefijo."db/db.mlPais.php");
require("./".$prefijo."db/db.mlSession.php");
require("./".$prefijo."db/db.mlUsuario.php");
require("./".$prefijo."db/db.mlVistaUsuario.php");
?>